# Generated by Django 6.0 on 2025-12-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_bookedticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='booked_seats',
        ),
    ]
