# Generated by Django 6.0 on 2025-12-11 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_session_booked_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cinemas/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
    ]
